version: '2'

services:
  goservice:
    image: flowup/docker-workshop
    volumes:
     - ./data:/app/data
    environment:
     - VIRTUAL_HOST=as.localhost
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
     - "80:80"
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro

